"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from datetime import timedelta
from dotenv import load_dotenv

load_dotenv()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG") == "True"

ALLOWED_HOSTS = []

# Application definition
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",  ###
    "rest_framework_simplejwt",  ###
    "drf_spectacular",  ###
    "django_celery_results",  ###
    "accounts",  ###
    "gallery",  ###
    "corsheaders",  ### https://pypi.org/project/django-cors-headers/
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",  ###
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "backend.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

### BELOW LINES ARE ADDED BY ME
###__________LOCAL_DJANGO_________(https://medium.com/django-unleashed/working-and-configuring-media-files-in-django-0c2fa7b97a1e)
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"
USE_MINIO = False  # most important line

###__________Django REST Framework_________
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": ("rest_framework.permissions.IsAuthenticated",),
    "EXCEPTION_HANDLER": "backend.exceptions.custom_exception_handler",
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}
###__________Browsable UI for ImageField_________ https://stackoverflow.com/questions/67521669/using-filefield-imagefield-with-swagger-ui-and-drf-spectacular
SPECTACULAR_SETTINGS = {"COMPONENT_SPLIT_REQUEST": True}

###__________Simple JWT_________
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=1),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "AUTH_HEADER_TYPES": ("Bearer",),
}


###__________CORSHEADERS_________(https://pypi.org/project/django-cors-headers/)
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]
# CORS_ORIGIN_ALLOW_ALL = True
FASTAPI_SERVICE_URL = os.environ.get("FASTAPI_SERVICE_URL")

###__________MINIO_________(https://pypi.org/project/django-minio-backend/)
if USE_MINIO:
    INSTALLED_APPS.append(
        "django_minio_backend"
    )  ### https://pypi.org/project/django-minio-backend/
    # if you remove above line,inspite of running minio server,it will not work
    DEFAULT_FILE_STORAGE = "django_minio_backend.models.MinioBackend"
    from typing import List, Tuple

    STORAGES = {  # -- ADDED IN Django 5.1
        "default": {
            "BACKEND": "django_minio_backend.models.MinioBackend",
        },
        "staticfiles": {  # -- ADD THESE LINES FOR STATIC FILES SUPPORT
            "BACKEND": "django_minio_backend.models.MinioBackendStatic",  # python manage.py collectstatic for DRF
        },
    }

    MINIO_ENDPOINT = "127.0.0.1:9000"  # Docker running at
    MINIO_ACCESS_KEY = "minioadmin"  # My MINIO username
    MINIO_SECRET_KEY = "minioadmin"  # My MINIO password

    MINIO_PUBLIC_BUCKETS = ["media", "static"]  # Buckets for media and static files
    MINIO_MEDIA_FILES_BUCKET = "media"  # replacement for MEDIA_ROOT
    MINIO_STATIC_FILES_BUCKET = "static"  # replacement for STATIC_ROOT
    MINIO_POLICY_HOOKS: List[Tuple[str, dict]] = []

    MINIO_USE_HTTPS = False  # Mandatiry parameter
    MINIO_BUCKET_CHECK_ON_SAVE = True  # Default: Autocreates bucket if not present
    MINIO_CONSISTENCY_CHECK_ON_START = True  # Health & consistency check

###_________Celery Configuration_________
CELERY_BROKER_URL = "redis://localhost:6379/0"
CELERY_RESULT_BACKEND = "redis://localhost:6379/0"


CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TIMEZONE = "UTC"
CELERY_TASK_TRACK_STARTED = True
# Store results in Django DB (needs django-celery-results)
CELERY_RESULT_BACKEND = "django-db"
